# Generated by Django 6.0.5 on 2026-06-01 17:44

import django.db.models.deletion
import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=12)),
                ('piece_count', models.PositiveIntegerField(default=1, verbose_name='تعداد قطعه')),
                ('additional_description', models.TextField(blank=True, null=True, verbose_name='توضیحات اضافی')),
                ('order_document', models.FileField(upload_to=order.models.order_file_path, verbose_name='فایل سفارش')),
                ('status', models.CharField(choices=[('pending', 'در حال انجام'), ('done', 'تمام شده')], default='pending', max_length=20, verbose_name='وضعیت سفارش')),
                ('is_archived', models.BooleanField(default=False, verbose_name='آرشیو شده')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('update_date', models.DateField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('CNC تراشکاری', 'CNC تراشکاری'), ('CNC فرزکاری', 'CNC فرزکاری'), ('Anodizing', 'Anodizing'), ('Laser hack', 'Laser hack')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaserHackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('', 'انتخاب کنید'), ('aluminium', 'آلومینیوم'), ('plain_steel', 'فولاد ساده'), ('stainless_steel', 'استنلس استیل'), ('brass', 'برنج'), ('copper', 'مس'), ('titanium', 'تیتانیوم'), ('plastic', 'پلاستیک'), ('wood', 'چوب'), ('other', 'سایر مواد')], default='', max_length=50, verbose_name='نوع متریال')),
                ('width_mm', models.PositiveIntegerField(verbose_name='عرض (mm)')),
                ('Lenght_mm', models.PositiveIntegerField(verbose_name='طول (mm)')),
                ('Engraving_depth', models.CharField(choices=[('سطحی', 'سطحی'), ('نیمه عمیق', 'نیمه عمیق'), ('عمیق', 'عمیق')], default='', max_length=40)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='LaserHack_data', to='order.ordermodel')),
            ],
        ),
        migrations.CreateModel(
            name='CNCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('', 'انتخاب کنید'), ('aluminium', 'آلومینیوم'), ('plain_steel', 'فولاد ساده'), ('stainless_steel', 'استنلس استیل'), ('brass', 'برنج'), ('copper', 'مس'), ('titanium', 'تیتانیوم'), ('plastic', 'پلاستیک'), ('wood', 'چوب'), ('other', 'سایر مواد')], default='', max_length=50, verbose_name='نوع متریال')),
                ('width_mm', models.PositiveIntegerField(verbose_name='عرض (mm)')),
                ('Lenght_mm', models.PositiveIntegerField(verbose_name='طول (mm)')),
                ('height_mm', models.PositiveIntegerField(verbose_name='ارتفاع (mm)')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CNC_data', to='order.ordermodel')),
            ],
        ),
        migrations.CreateModel(
            name='Anodizingdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anodizing_shape', models.CharField(choices=[('', 'انتخاب کنید'), ('مکعب توپر', 'مکعب توپر'), ('باکس توخالی(بدون یک وجه)', 'باکس توخالی(بدون یک وجه)'), ('استوانه توپر', 'استوانه توپر'), ('استوانه توخالی', 'استوانه توخالی')], default='', max_length=80, verbose_name=' شکل آنودایزینگ')),
                ('material', models.CharField(choices=[('', 'انتخاب کنید'), ('aluminium 1050', '1050 آلومینیوم'), ('aluminium 2024', '1050 آلومینیوم'), ('aluminium 3105', '1050 آلومینیوم'), ('aluminium 5052', '1050 آلومینیوم'), ('aluminium 6061', '1050 آلومینیوم'), ('aluminium 6063', '1050 آلومینیوم'), ('aluminium 7075', '1050 آلومینیوم'), ('titanium Grade 2', 'Grade 2 تیتانیوم '), ('titanium Grade 5 (Ti-6Al-4v)', 'Grade 5 (Ti-6Al-4v) تیتانیوم '), ('titanium Grade 23 (Ti-6Al-4v-ELI)', 'Grade 23 (Ti-6Al-4v-ELI) تیتانیوم ')], default='', max_length=50, verbose_name='نوع متریال')),
                ('PardakhtSath', models.CharField(choices=[('', 'انتخاب کنید'), ('(Glossy) براق', '(Glossy) براق'), ('(Matte) مات', '(Matte) مات')], default='', max_length=80, verbose_name=' شکل آنودایزینگ')),
                ('color', models.CharField(choices=[('green', 'سبز'), ('blue', 'آبی'), ('red', 'قرمز'), ('silver', 'سیلور'), ('purple_blue', 'بنفش آبی'), ('purple_red', 'بنفش قرمز'), ('gold', 'طلایی'), ('black', 'مشکی'), ('black_hard', 'مشکی هارد'), ('olive_hard', 'زیتونی هارد')], max_length=20, verbose_name='رنگ')),
                ('width_mm', models.PositiveIntegerField(verbose_name='عرض (mm)')),
                ('Lenght_mm', models.PositiveIntegerField(verbose_name='طول (mm)')),
                ('height_mm', models.PositiveIntegerField(verbose_name='ارتفاع (mm)')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Anodizing_data', to='order.ordermodel')),
            ],
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.service'),
        ),
    ]
